name: Ejemplo de Composite Action

on: [push]

jobs:
    say-hello:
        runs-on: ubuntu latest

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: example
                ports:
                    - 3306:3306
                # options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3