name: Hola Mundo

# Controls when the action will run. Triggers the workflow on push or pull request
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"

      - name: touch file
        run: touch hola.txt

      - name: Set text
        run: echo "Hola Mundo" >> hola.txt

      - name: Read file
        run: cat hola.txt

  other:
    runs-on: ubuntu-latest
    steps:
      - name: LS
        run: ls -al